# Default values for ekoparty-flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: tty0/flask_app
  pullPolicy: Always
  tag: "1.0"

service:
  type: ClusterIP
  port: 8000

limits:
  cpu: 0.2
  memory: 128Mi
requests:
  cpu: 0.4
  memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

conf:
  salute: "better ask for forgiveness than permission"
  header: "https://ekoparty.org/web/image/1309/badges.jpg"
