---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "ekoparty-flask-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
  name: flask-app
  namespace: default
spec:
  rules:
    - host: flask-app.tty0.guru
      http:
        paths:
          - backend:
              serviceName: ekoparty-flask-app
              servicePort: 8000
            path: /
