---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "flask-ingress"
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
    external-dns.alpha.kubernetes.io/hostname: tty0.guru
    external-dns.alpha.kubernetes.io/ttl: "120"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/default-backend: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: flask-app
  namespace: default
spec:
  tls:
    - hosts:
      - flask-app.tty0.guru
      - email.tty0.guru
      - dc-solutions.tty0.guru
      secretName: ingress-tls
  rules:
  - host: "flask-app.tty0.guru"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ekoparty-flask-app
            port:
              number: 8000
  - host: "email.tty0.guru"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ekoparty-flask-app
            port:
              number: 8000
  - host: "dc-solutions.tty0.guru"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ekoparty-flask-app
            port:
              number: 8000
