---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "ekoparty-flask-app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
    external-dns.alpha.kubernetes.io/hostname: tty0.guru
    external-dns.alpha.kubernetes.io/ttl: "120"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/redirect-to-https: "true"
    nginx.ingress.forwarded-for-header: X-Forwarded-For
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/default-backend: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/x-forwarded-proto: https
    nginx.ingress.use-forwarded-headers: "true"
    nginx.org/hsts: "true"
    nginx.org/hsts-include-subdomains: "true"
  name: flask-app
  namespace: default
spec:
  rules:
    - host: flask-app.tty0.guru
      http:
        paths:
          - backend:
              serviceName: ekoparty-flask-app
              servicePort: 8000
            path: /
  tls:
    - hosts:
      - flask-app.tty0.guru
      secretName: ingress-tls

