# Default values for demo-flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: default

image:
  repository: tty0/flask_app
  pullPolicy: Always
  tag: "1.1"

service:
  type: ClusterIP
  port: 8000

limits:
  cpu: 0.2
  memory: 128Mi
requests:
  cpu: 0.4
  memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  hostname: flask-app.tty0.guru
  class: nginx
  path: "/"
  dnsController:
    enabled: true
    hostname: tty0.guru
    ttl: "120"
  certManager:
    enabled: true
    issuer: "letsencrypt-prod"
    acmeChallenge: "http01"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/default-backend: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"

conf:
  ##----------------------------------------------------------------------
  ## Demo salute
  ##----------------------------------------------------------------------
  salute: "One Ring to link them all, One Ring to ping them, one Ring to bring them all and in the darkness sniff them."
  ##----------------------------------------------------------------------
  # Initial header
  header: "https://image.spreadshirtmedia.net/image-server/v1/compositions/T1040A14PA2641PT26X30Y7D126917021FS8999/views/1,width=650,height=650,appearanceId=14,backgroundColor=fff.jpg"
  ##----------------------------------------------------------------------
  ## Demo header
  ##----------------------------------------------------------------------
  #header: "https://media.revistagq.com/photos/5ca5facbf552a15f9432edfe/master/w_1600,c_limit/mr_robot_5832.jpg"

