# Default values for ekoparty-flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: tty0/flask_app
  pullPolicy: Always
  tag: "1.1"

service:
  type: ClusterIP
  port: 8000

limits:
  cpu: 0.2
  memory: 128Mi
requests:
  cpu: 0.4
  memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

conf:
  salute: "Hello Ekoparty!"
  ##----------------------------------------------------------------------
  ## Demo salute
  ##----------------------------------------------------------------------
  #salute: "One Ring to link them all, One Ring to ping them, one Ring to bring them all and in the darkness sniff them."
  ##----------------------------------------------------------------------
  # Initial header
  #header: "https://ekoparty.org/web/image/1309/badges.jpg"
  ##----------------------------------------------------------------------
  ## Demo header
  ##----------------------------------------------------------------------
  header: "https://64.media.tumblr.com/tumblr_mdancgV98b1r4xjo2o1_500.gif"

