name: Build demo-flask-app

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run flake8
        uses: julianwachholz/flake8-action@v1
        with:
          checkName: "Python Lint"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  scan:
    name: Security scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/tty0/flask-app:1.1 .
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/tty0/flask_app:1.1'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
    
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs: scan
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: tty0/flask_app
          tags: 1.1     
